#!/usr/bin/env bash
# =============================================================================
# audit-web-submodule.sh — P0'-a front-end (web submodule) read-only audit
#
# Motivation (组会纪要 §3.2 / D11):
#   - The `web/` git submodule is a separate repo (HelixFlow-WEB). We want a
#     quick, reproducible audit without populating the submodule inside the
#     active worktree — that would risk file pollution across coder branches.
#   - Therefore: clone into a tmpfs / scratch directory, inspect 6 dimensions,
#     emit a Markdown report, and auto-clean the scratch tree.
#
# Output:
#   ~/Documents/knowledge/research/_tmp_helixflow_web_audit.md
#   (override with HELIXFLOW_AUDIT_OUT=/path/to/file.md)
#
# Dimensions audited:
#   1. LOC (lines of code) by top-level directory + overall total
#   2. React version (from package.json dependencies)
#   3. ReactFlow version
#   4. Other key deps (axios, antd, tailwind, redux, etc.)
#   5. Field-consumer grep — search for code that reads/writes HelixFlow
#      backend fields ("flows", "operators", "fields", "helixflow/").
#   6. npm audit (vulnerability scan)
#
# If the clone fails (network, auth), a placeholder report is still emitted
# so the downstream CI artifact step does not fail the job.
#
# Usage:
#   make web-audit              # via Makefile
#   scripts/audit-web-submodule.sh
#   HELIXFLOW_WEB_URL=<url> scripts/audit-web-submodule.sh
# =============================================================================

set -u

SUBMODULE_URL_DEFAULT="https://github.com/HelixFlow/HelixFlow-WEB.git"
SUBMODULE_URL="${HELIXFLOW_WEB_URL:-${SUBMODULE_URL_DEFAULT}}"

OUT_DIR_DEFAULT="${HOME}/Documents/knowledge/research"
OUT_FILE="${HELIXFLOW_AUDIT_OUT:-${OUT_DIR_DEFAULT}/_tmp_helixflow_web_audit.md}"

mkdir -p "$(dirname "${OUT_FILE}")"

# --- scratch dir: prefer tmpfs (/tmp) so the main worktree stays clean -------
SCRATCH_DIR="$(mktemp -d -t helixflow-web-audit-XXXXXX)"
cleanup() {
    rm -rf "${SCRATCH_DIR}"
}
trap cleanup EXIT

CLONE_DIR="${SCRATCH_DIR}/web"
AUDIT_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

emit_placeholder() {
    local reason="$1"
    cat > "${OUT_FILE}" <<MARKDOWN
# HelixFlow Web Submodule Audit

**Status**: ⚠️ placeholder — audit incomplete
**Date (UTC)**: ${AUDIT_DATE}
**Submodule URL**: ${SUBMODULE_URL}
**Reason**: ${reason}

> This file was generated by \`scripts/audit-web-submodule.sh\` when the
> front-end submodule could not be cloned (network unavailable, auth
> required, or repository private). Re-run once the blocker is resolved:
>
>     make web-audit
>
> Expected sections (filled in on a successful run):
>   1. LOC breakdown
>   2. React version
>   3. ReactFlow version
>   4. Key frontend dependencies
>   5. Field-consumer grep (flows / operators / fields / helixflow/)
>   6. npm audit (vulnerabilities)
MARKDOWN
    echo "[audit] placeholder report written to ${OUT_FILE}" >&2
}

# --- 1. clone (read-only, shallow) ------------------------------------------
echo "[audit] cloning ${SUBMODULE_URL} → ${CLONE_DIR} (depth=1) …"
if ! git clone --depth=1 --quiet "${SUBMODULE_URL}" "${CLONE_DIR}" 2>"${SCRATCH_DIR}/clone.err"; then
    reason="git clone failed: $(tr '\n' ' ' < "${SCRATCH_DIR}/clone.err" | head -c 300)"
    emit_placeholder "${reason}"
    exit 0
fi

cd "${CLONE_DIR}" || {
    emit_placeholder "cannot enter cloned directory"
    exit 0
}

# --- 2. LOC -----------------------------------------------------------------
loc_total=0
loc_breakdown=""
if [ -d src ]; then
    while IFS= read -r -d '' f; do
        n=$(wc -l < "$f" 2>/dev/null || echo 0)
        loc_total=$((loc_total + n))
    done < <(find src -type f \( -name '*.ts' -o -name '*.tsx' -o -name '*.js' -o -name '*.jsx' -o -name '*.vue' \) -print0)
fi

for top_dir in src public scripts; do
    [ -d "${top_dir}" ] || continue
    sub_loc=0
    while IFS= read -r -d '' f; do
        n=$(wc -l < "$f" 2>/dev/null || echo 0)
        sub_loc=$((sub_loc + n))
    done < <(find "${top_dir}" -type f \( -name '*.ts' -o -name '*.tsx' -o -name '*.js' -o -name '*.jsx' -o -name '*.vue' -o -name '*.css' -o -name '*.scss' -o -name '*.json' \) -print0)
    loc_breakdown="${loc_breakdown}- \`${top_dir}/\`: ${sub_loc} lines
"
done

# --- 3/4. dependency versions via package.json ------------------------------
pkg_json="package.json"
react_ver="<missing>"
reactflow_ver="<missing>"
key_deps=""
if [ -f "${pkg_json}" ]; then
    # Python one-liner is more robust than sed for keys containing "/" or "@"
    # and for the nested dependency/devDependency lookups.
    extract() {
        local key="$1"
        python3 - "${pkg_json}" "${key}" <<'PY' 2>/dev/null
import json, sys
path, key = sys.argv[1], sys.argv[2]
try:
    with open(path) as fh:
        pkg = json.load(fh)
except Exception:
    print("<missing>")
    sys.exit(0)
for section in ("dependencies", "devDependencies", "peerDependencies"):
    if section in pkg and key in pkg[section]:
        print(pkg[section][key])
        sys.exit(0)
print("<missing>")
PY
    }
    react_ver=$(extract 'react')
    reactflow_ver=$(extract 'reactflow')
    if [ "${reactflow_ver}" = "<missing>" ]; then
        reactflow_ver=$(extract '@reactflow/core')
    fi
    for dep in axios antd tailwindcss @reduxjs/toolkit zustand react-router-dom vite webpack; do
        v=$(extract "${dep}")
        key_deps="${key_deps}- \`${dep}\`: ${v}
"
    done
fi

# --- 5. field-consumer grep -------------------------------------------------
field_hits=""
if [ -d src ]; then
    # Limit to first 40 hits per dimension to keep report readable
    for pat in 'helixflow/' '/flows' '/operators' '"fields"' 'appstate'; do
        hits=$(grep -rnI --include='*.ts' --include='*.tsx' --include='*.js' --include='*.jsx' --include='*.vue' "${pat}" src 2>/dev/null | head -40 || true)
        field_hits="${field_hits}### pattern: \`${pat}\`

\`\`\`
${hits:-<no matches>}
\`\`\`

"
    done
fi

# --- 6. npm audit -----------------------------------------------------------
npm_audit_summary="<npm not available or audit skipped>"
if command -v npm >/dev/null 2>&1 && [ -f "${pkg_json}" ]; then
    if npm install --ignore-scripts --no-audit --silent --prefer-offline 2>/dev/null; then
        npm_audit_summary=$(npm audit --json 2>/dev/null | head -100)
    else
        npm_audit_summary="<npm install failed — audit skipped>"
    fi
fi

# --- emit report ------------------------------------------------------------
{
    echo "# HelixFlow Web Submodule Audit"
    echo
    echo "**Status**: ✅ complete"
    echo "**Date (UTC)**: ${AUDIT_DATE}"
    echo "**Submodule URL**: ${SUBMODULE_URL}"
    echo "**Commit (HEAD)**: $(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
    echo
    echo "---"
    echo
    echo "## 1. LOC"
    echo
    echo "- **Total (src/ code files)**: ${loc_total} lines"
    echo
    if [ -n "${loc_breakdown}" ]; then
        echo "${loc_breakdown}"
    fi
    echo
    echo "## 2. React version"
    echo
    echo "- \`react\`: ${react_ver}"
    echo
    echo "## 3. ReactFlow version"
    echo
    echo "- \`reactflow\` / \`@reactflow/core\`: ${reactflow_ver}"
    echo
    echo "## 4. Key dependencies"
    echo
    if [ -n "${key_deps}" ]; then
        echo "${key_deps}"
    else
        echo "<no package.json found>"
    fi
    echo
    echo "## 5. Field-consumer grep"
    echo
    echo "${field_hits:-<src/ not found>}"
    echo
    echo "## 6. npm audit"
    echo
    echo "\`\`\`json"
    echo "${npm_audit_summary}"
    echo "\`\`\`"
    echo
    echo "---"
    echo "_Generated by \`scripts/audit-web-submodule.sh\`._"
} > "${OUT_FILE}"

echo "[audit] report written to ${OUT_FILE}" >&2
